### PR TITLE
Changed audio default to unmute

### PR DESCRIPTION
**Pull request by baznamit**
I think its better to play audio automatically after clicking on channel, instead of clicking on unmute button.

### CODE REVIEW

**Comment by nrjdalal** [comment]
did you check if it is working? it doesn't work on some browsers, unmuted={true} for a reason, need alternatives for that, let me know if it works in firefox and chrome and edge, afari if you can test, then will update the code

**Comment by baznamit** [comment]
I know in documentation its written that video must be muted for playing, but I have tested, video play automatically with audio default unmute,

**Comment by baznamit** [comment]
Checked it with Chrome, Opera, Edge and Firefox.

**Comment by nrjdalal** [comment]
I’ll check and update shortly then. Thank you.

**Comment by baznamit** [comment]
Any update?

**Pull request merged**
